### ISSUE TITLE
Add support for pre-defined adsorbates

### ISSUE THREAD

**Issue by arosen93** [arosen93/mof-adsorbate-initializer#7]
Currently, MAI supports the bottom-up construction of monatomic, diatomics, and triatomics. However, it would be desirable to have support for any predefined adsorbate, as provided via an ASE Atoms object. This will allow for more flexibility and the handling of complex problems beyond small molecules. Algorithm should be nearly identical to before, just using a predefined Atoms object and not one constructed by the user.

**Comment by Andrew-S-Rosen** [comment]
Won't fix. See https://github.com/haoyuanchen/mof-big-adsorbate-initializer.
